BINANCE_API_KEY = 'BINANCE_API_KEYNİZ'
BINANCE_SECRET = 'BINANCE_SECRETNİZ'
TELEGRAM_TOKEN = 'TELEGRAM_BOT_TOKEN'
TELEGRAM_CHAT_ID = 'TELEGRAM_CHAT_ID'
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'XRP/USDT', 'ADA/USDT', 'DOGE/USDT', 'SOL/USDT', 'TRX/USDT', 'DOT/USDT', 'MATIC/USDT', 'LTC/USDT', 'AVAX/USDT', 'LINK/USDT', 'ATOM/USDT', 'UNI/USDT', 'XLM/USDT', 'ETC/USDT', 'XMR/USDT', 'ALGO/USDT', 'FIL/USDT']